### ISSUE TITLE
Old link to fontawesome sheet dead

### ISSUE THREAD

**Issue by walfrat** [kordamp/ikonli#58] opened 2020-01-07 10:36 UTC
Hello, 

The old link I used to find all the available icons doesn't work anymore.

The link was : https://aalmiray.github.io/ikonli/cheat-sheet-fontawesome5.html

I have search in this repo, the fontawesome5 adoc document seems broken by missing some inner part.

Furthermore when I try to go to the guide, I get an error : seems like the site kordamp.org is not up.

**Comment by aalmiray** [comment] 2020-01-07 10:42
Duplicate of #57.

The project has moved to the Kordamp organization, as such, all links that used to resolve from https://aalmiray.github.io now resolve against https://kordamp./github.io or http://kordamp.org/ikonli

**Closed by aalmiray** 2020-01-07 10:42 UTC
